spring:
    kafka:
        bootstrap-servers: localhost:9092
        topic:
            name: insurance-policies-topic

    data:
        mongodb:
            host: localhost
            port: 27017
            database: kafka-data-pipeline